name: kartal
description: Kartal is an extension package for easy to use at app development
  time. You can access more features with primitive variables(context, string
  etc.).
version: 3.3.0
repository: https://github.com/VB10/kartal

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.16.0
  device_info_plus: ^9.0.2
  diacritic: ^0.1.3
  flutter:
    sdk: flutter
  mask_text_input_formatter: ^2.0.0
  mime: ^1.0.0
  package_info_plus: ^4.0.2

  share_plus: ^7.0.2
  share_plus_web: ^3.1.0
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1
  mockito: ^5.4.2

flutter:
  uses-material-design: true
