name: kartal
description: Kartal is an extension package for easy to use at app development
  time. You can access more features with primitive variables(context, string
  etc.).
version: 4.0.0-dev3
issue_tracker: https://github.com/vb10/kartal/issues
repository: https://github.com/VB10/kartal
screenshots:
  - description: 'City of Kartal, Istanbul'
    path: screen_shots/kartal.jpeg

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.16.0
  device_info_plus: ^9.0.2
  diacritic: ^0.1.3
  dio: ^5.3.3
  flutter:
    sdk: flutter
  html: ^0.15.4
  logger: ^2.0.2
  mask_text_input_formatter: ^2.0.0
  mime: ^1.0.0
  package_info_plus: ^5.0.1
  share_plus: ^7.0.2
  share_plus_web: ^3.1.0
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true
